Schedule algorithm
Stout-2022-Capstone-Scheduler-Team/SchedulerApp pull request #18
Opened 2022-10-17 19:48 UTC by Jpvandyck1

2022-10-18 03:48 UTC, JoelYoung01 requested changes
Looking great, just split up the entities into their own 'entities' directory, see my other comment!

2022-10-18 03:48 UTC, JoelYoung01 commented on services/types.ts
> +export class Time {
Could we get all these types broken out into their own files, in a new 'entities' directory? Ideally, name them after the type they represent. To still include the functionality to import all with a single import statement, add an 'index.ts' file that explicitly exports each type (syntax: export * from "./[type].ts";, or at least something similar)

2022-10-18 14:07 UTC, the10thWiz approved these changes

2022-10-19 17:18 UTC, JoelYoung01 approved these changes

2022-10-19 17:19 UTC, merged