Start page
Stout-2022-Capstone-Scheduler-Team/SchedulerApp pull request #23
Opened 2022-10-24 20:15 UTC by LouieMattia

2022-10-24 22:14 UTC, the10thWiz approved these changes

2022-10-26 17:35 UTC, JoelYoung01 requested changes
Looking good so far, just a small change to the underlying setup of the index page and you will be good to go!

2022-10-26 17:35 UTC, JoelYoung01 commented on pages/index.tsx
> +      <Stack spacing={2} sx={{ width: 300 }}>
Please reduce this triple nested Stack to a single stack element.

2022-10-26 18:03 UTC, JoelYoung01 approved these changes

2022-10-26 18:12 UTC, merged